### ISSUE TITLE
Image cropper example broken?

### ISSUE THREAD

**Issue by jaens** [mint-lang/mint-ui#39]
This is a screenshot (after resizing to 100px to make it more obvious) - looks like something is not right:

![image](https://user-images.githubusercontent.com/639345/166298022-a128d059-837b-4d51-b656-0356d9d7fe74.png)

Address: https://ui.mint-lang.com/components/ui-image-crop
Browser: Firefox 99

**Comment by gdotdesign** [comment]
It's fixed now.
