### ISSUE TITLE
Color Picker: Changes width when dragging color handle 

### ISSUE THREAD

**Issue by JohannesKaufmann** [mint-lang/mint-ui#5]
First of all, I’m amazed at the quality & quantity of the components. That's really astonishing 🎉

---

When dragging around the color handle on the [Color Picker](https://ui.mint-lang.com/components/ui-color-picker), the hex value changes. Since not all characters are rendered with the same width, the overall width of the button changes. 

_Expected_: Button & Popup keep the same width, regardless of the button content.

_Actual_: The button changes the width and then the popup also changes the width.

One way this could be fixed is by changing the font family to a **monospaced** font on the `span`. Then the individual characters would be the same width regardless of the actual character.

_Tested with Firefox Developer Edition (88.0b9) and Chrome (90.0.4430.85) on MacOS Big Sur (11.2.3)._

https://user-images.githubusercontent.com/20886667/115682967-411f0900-a356-11eb-95a3-5e166496d457.mov

**Comment by gdotdesign** [comment]
> First of all, I’m amazed at the quality & quantity of the components. That's really astonishing :tada:

Thank you! :blush:

----------

Also thank you for detailed issue! 

> One way this could be fixed is by changing the font family to a **monospaced** font on the `span`. Then the individual characters would be the same width regardless of the actual character.

I like that solution, that is probably what we are going to use :slightly_smiling_face:
