### ISSUE TITLE
Checkout Example: Country-Select cut-off

### ISSUE THREAD

**Issue by JohannesKaufmann** [mint-lang/mint-ui#6]
https://ui.mint-lang.com/examples/checkout

The country `select` is partially cut-off.

_Tested with Firefox Developer Edition (88.0b9) and Chrome (90.0.4430.85) on MacOS Big Sur (11.2.3)._
<img width="688" alt="Screenshot 2021-04-22 at 10 39 46" src="https://user-images.githubusercontent.com/20886667/115683806-18e3da00-a357-11eb-910d-0019780a075d.png">

---

BTW: Selecting a country on such lists is always really annoying. If I want to select "Germany" (sometimes they also translate it, then I would have to search for "Deutschland"), I need to find the item somewhere in the list. Luckily - at least with a native select - I can press "G" on my keyboard which brings me to that section. But unfortunately, that doesn't seem to be supported with `Ui.Select`.

**Comment by gdotdesign** [comment]
Thanks for letting me know! I'll change it so it opens in the other direction.

> BTW: Selecting a country on such lists is always really annoying. If I want to select "Germany" (sometimes they also translate it, then I would have to search for "Deutschland"), I need to find the item somewhere in the list. Luckily - at least with a native select - I can press "G" on my keyboard which brings me to that section. But unfortunately, that doesn't seem to be supported with `Ui.Select`.

It's a planned feature to add at some point!
