### ISSUE TITLE
[FEATURE] format property for Ui.RelativeTime and Ui.DatePicker

### ISSUE THREAD

**Issue by cindRoberta** [mint-lang/mint-ui#8]
the format currently used is "YYYY-MM-DD". The format property would make possible the inputs have the formats:

- "YYYY-MM-DD"
- "YYYY-DD-MM"
- "MM-DD-YYYY"
- "MM-YYYY-DD"
- "DD-MM-YYYY"
- "DD-YYYY-MM"

___

- "YYYY/MM/DD"
- "YYYY/DD/MM"
- "MM/DD/YYYY"
- "MM/YYYY/DD"
- "DD/MM/YYYY"
- "DD/YYYY/MM"

**Comment by gdotdesign** [comment]
We can add a `format : String` property to control how the time is formatted and also a `formatter : Function(Time, Html)` property which would allow even more control.

**Comment by gdotdesign** [comment]
Added in 88d1c03194575e7e882cd7db1e8227623b388580

**Comment by gdotdesign** [comment]
Released in [4.0.0](https://github.com/mint-lang/mint-ui/releases/tag/4.0.0) :rocket:
